// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOZLRbspRMDi-GC4DH8SnwTtDxm2EqMxQ',
    appId: '1:450420681032:web:0e61ed5be34ea287e3ab7d',
    messagingSenderId: '450420681032',
    projectId: 'socioconnect-3a099',
    authDomain: 'socioconnect-3a099.firebaseapp.com',
    storageBucket: 'socioconnect-3a099.appspot.com',
    measurementId: 'G-WBDRZQS7HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMAhaXdTp2iepWGKXwpLyqjD3OqKw7tsA',
    appId: '1:450420681032:android:a3245f6e22db2994e3ab7d',
    messagingSenderId: '450420681032',
    projectId: 'socioconnect-3a099',
    storageBucket: 'socioconnect-3a099.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvoKxf7MRGL1FnG2vcg7a4wEQ-EabRZrI',
    appId: '1:450420681032:ios:71799900da9f6180e3ab7d',
    messagingSenderId: '450420681032',
    projectId: 'socioconnect-3a099',
    storageBucket: 'socioconnect-3a099.appspot.com',
    androidClientId: '450420681032-nn8qff4bjg7j012sloj48f8vain4ebii.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvoKxf7MRGL1FnG2vcg7a4wEQ-EabRZrI',
    appId: '1:450420681032:ios:71799900da9f6180e3ab7d',
    messagingSenderId: '450420681032',
    projectId: 'socioconnect-3a099',
    storageBucket: 'socioconnect-3a099.appspot.com',
    androidClientId: '450420681032-nn8qff4bjg7j012sloj48f8vain4ebii.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOZLRbspRMDi-GC4DH8SnwTtDxm2EqMxQ',
    appId: '1:450420681032:web:23bb6d28a02c289fe3ab7d',
    messagingSenderId: '450420681032',
    projectId: 'socioconnect-3a099',
    authDomain: 'socioconnect-3a099.firebaseapp.com',
    storageBucket: 'socioconnect-3a099.appspot.com',
    measurementId: 'G-M6YESC6HRZ',
  );
}
